### ISSUE TITLE
404 on osinfo

### ISSUE THREAD

**Issue by Jarvvski** [gardotd426/regolith-de#24] opened 2021-09-19 22:04 UTC
Noticed this while running the makepkg

```
error: failed retrieving file 'osinfo-db-20210531-1-any.pkg.tar.zst' from manjaro.moson.org : The requested URL returned error: 404
error: failed retrieving file 'osinfo-db-20210531-1-any.pkg.tar.zst' from mirrors.opensource.is : The requested URL returned error: 404
error: failed retrieving file 'osinfo-db-20210531-1-any.pkg.tar.zst' from manjaro.mirror.garr.it : The requested URL returned error: 404
error: failed retrieving file 'osinfo-db-20210531-1-any.pkg.tar.zst' from ftp.vectranet.pl : The requested URL returned error: 404
error: failed retrieving file 'osinfo-db-20210531-1-any.pkg.tar.zst' from mirror.easyname.at : The requested URL returned error: 404
error: failed retrieving file 'osinfo-db-20210531-1-any.pkg.tar.zst' from repo.ialab.dsu.edu : The requested URL returned error: 404
error: failed retrieving file 'osinfo-db-20210531-1-any.pkg.tar.zst' from mirror.rise.ph : The requested URL returned error: 404
(37/37) checking keys in keyring 
```

**Comment by gardotd426** [comment] 2021-09-19 23:46
Huh? I think you've messed up something, because `osinfo-db-20210531-1-any.pkg.tar.zst` isn't in my PKGBUILD at all. That error doesn't come from just cloning the repo and running `makepkg`. Something else is going on that's unrelated to my PKGBUILD.

**Comment by Jarvvski** [comment] 2021-09-20 00:09
All I ran was:

```
git clone git@github.com:gardotd426/regolith-de.git
cd regolith-de
makepkg -si
```

**Comment by gardotd426** [comment] 2021-09-20 00:35
Ahh, I figured it out. 

osinfo-db is a dependency like 5 steps down. It goes like this:

Regolith DE depends on gnome-flashback. Which depends on gnome-panel. Which depends on nautilus. Which depends on tracker3-miners. Which depends on libosinfo, which depends on osinfo-db.

But still the problem isn't with my PKGBUILD. It's with your mirrors/pacman database. `osinfo-db-20210531-1-any` isn't the current version in the Manjaro repositories. It's `osinfo-db-20210903-1-any`. So you haven't updated your mirrors recently enough. You need to run `sudo pacman -Syy && sudo pacman -Fyy`, and then re-run the PKGBUILD with `makepkg -sfi`.

**Comment by Jarvvski** [comment] 2021-09-20 00:37
Ah cool, thanks for deep diving.

I'll check it out tomorrow and have a second pass at it.

Do you plan on moving this into the AUR at some point? Or are you waiting on the discussion I see on a regolith that's detached from Ubuntu.

**Comment by gardotd426** [comment] 2021-09-20 00:39
Well, I'm gonna go ahead and try to move everything to the new release that
Regolith had, but that always takes some time because there are usually
breakages I have to fix (which is just part of the porting process), and
once I do that I'll decide whether to move to the AUR now or wait and see
where the discussion goes.

**Comment by Jarvvski** [comment] 2021-09-20 00:41
Yeap, no rush - thanks for your energy on this. I've been using Regolith on a work system, due to being required to run Ubuntu. Found your package from seeing if I could easily just match my home manjaro install, instead of trying to merge my custom I3 with that found in regolith.

Again, much appreciated. Thanks.

**Comment by gardotd426** [comment] 2021-09-30 00:29
It's in the AUR now. Anyway I'm closing this as the original issue was never to do with my package.

**Closed by gardotd426** 2021-09-30 00:29 UTC
