### ISSUE TITLE
Question: How best to test?

### ISSUE THREAD

**Issue by JoshuaCrewe** [gardotd426/regolith-de#4] opened 2020-06-26 12:49 UTC
I found this repo via the issue over on the regolith-desktop repo. Very much enjoyed reading along with the progress in creating this PKGBUILD.

I am keen to test this out. I had hoped to get it spun up in a virtual machine before trialling it on any hardware. Forgive my inexperience but I am not sure what steps I might be missing.

I used Endeavor OS to get base and base-devel installed in a virtual machine (Virtualbox) Then cloned this repo and rand `makepkg -si` as the arch wiki says. It went and ran and downloaded all the software. Then I got a bit unstuck. Where to now? I rebooted thinking something might kick in but it didn't. I put `exec i2-gnome-flashback-session` into `.xinitrc` and did a `startx` which did boot into the DE but the keybindings didn't work and I couldn't get out or do anything.

I am doing this all on a tiny screen too as I couldn't get guest-additions-iso to figure out the screen size (I always have trouble with this and I really should sit down to learn properly how to get this sort of stuff working). What am I missing?

Thanks for taking the time to put this together!

**Comment by JoshuaCrewe** [comment] 2020-07-06 13:37
Well I can't be sure if I am doing this right but I have been trying to follow what has been said [here](https://github.com/regolith-linux/regolith-desktop/issues/169#issuecomment-642416832) and [here](https://github.com/regolith-linux/regolith-desktop/issues/169#issuecomment-642419065) which is to say putting `exec i3-gnome-flashback-session` in the `.xinitrc` which does load up a working i3 environment. 

There are a couple of things not working but I can't tell if they are actual bugs or I have done it wrong. I have a vanilla Arch from the ISO after the installation guide plus the PKGBUILD in this repo. I installed xorg, updated the .xinitrc and did a `startx`. 

I get some issues which I am happy to report seperately and debug if I can confirm I am taking the right approach to testing. These are quite minor like the help screen doesn't work and the scrolling can be a bit laggy. Whenever testing in a virtual machine I always get conflicts in keyboard mappings which can make testing hard and the lagging could be a mis configuration in the VM. The icons are a bit off on the default theme I think too. Anyway these are all things I can debug.

From what I can see and use it looks nice though! 🎉

**Comment by gardotd426** [comment] 2020-07-06 13:54
>These are quite minor like the help screen doesn't work and the scrolling can be a bit laggy. Whenever testing in a virtual machine I always get conflicts in keyboard mappings which can make testing hard and the lagging could be a mis configuration in the VM. The icons are a bit off on the default theme I think too. Anyway these are all things I can debug.

Compositing with picom doesn't work hardly at all in virtual machines, and it makes it almost unusable (run killall compton and see if your scrolling issues go away). DistroTube actually did a review of another boutique distro in a VM that was using Picom and he blamed the distro for the same thing, not knowing that it was the virtual machine's fault (he later made an apology video). 

On bare metal, it's really smooth. But you should be able to get a help menu with mod+shift+? I believe. 

No one was willing to help me really test shit, it was actually kind of annoying, everyone asked for this (I wasn't even anyone who originally asked for it to be ported) and said "oh I'll help debug!" and then when I wrote a functioning PKGBUILD (which took days because of how tedious this specific project is) I got one dude to help me clean up the PKGBUILD and like one or two people tried it and ran into like one issue and quit. So I haven't even bothered with anything in the past couple weeks, because I'm at an impasse. The PKGBUILD should be fully functional, but I'm not going to put it live on the AUR without actually having enough testing and being comfortable making it go live. You know what I mean?  And so far even after like 10 people on that thread said they wanted it so bad and were willing to help test/debug, once I got it done it was all crickets. 

But I still want and am more than willing to help get it finished (again, it's essentially done, I might need one or two more edits if this `remontoire` keybinding isn't working), but I need more people testing it. 

Is there any way you can make a 10GB secondary partition to try running it on bare metal? If not, just turn off compositing in the VM and it won't be as pretty, but it'll run a lot better. 

The main thing I want to figure out is the terminal. By default I was using st, but the problem is 1) when I try to use Regolith's fork of st, it acts really stupid and gives error messages, because they put some dumb patch in it that makes it freak out, but 2) vanilla st is a nightmare, and 3) I can use an aur build of st but I don't like having an AUR package as a dependency or at least I want as few of those as possible. 


Oh wait, that reminds me. I can't have any AUR packages as dependencies, THAT'S why you currently don't have any help menu! See, once it goes live on the AUR and you use an AUR helper like yay, it'll pull in the dependencies, including aur ones. But right now, when you just clone the PKGBUILD and run makepkg, that won't work, the PKGBUILD will fail because `makepkg` can't check the AUR, so it'll say `package not found` and abort. So I had to remove remontoire until it goes live on the AUR, at which point I'll re-add it. So go ahead and install `remontoire-git` from the AUR, and restart the VM or at least log out and back in. And you should be good to go!

**Comment by gardotd426** [comment] 2020-07-06 13:56
Yeah I just checked the PKGBUILD and I did indeed remove remontoire because of what I mentioned above. Install `remontoire-git` from the AUR and you should have your help menu back, please report back and let me know if that works. Make sure you at least log out and back in before trying it because I think it's daemon-based and the daemon starts when you log in.

**Comment by JoshuaCrewe** [comment] 2020-07-06 14:54
> Install remontoire-git from the AUR and you should have your help menu back, please report back and let me know if that works.

Ha! I think we figured this out at the same time. I did a bit of looking around and found that was the package running the help screen. It does work fine when installing `remontoire-git` so that is easy!

> No one was willing to help me really test shit, it was actually kind of annoying, everyone asked for this (I wasn't even anyone who originally asked for it to be ported) and said "oh I'll help debug!" and then when I wrote a functioning PKGBUILD (which took days because of how tedious this specific project is) I got one dude to help me clean up the PKGBUILD and like one or two people tried it and ran into like one issue and quit.

I found this repo through that thread and flipping LOVED reading it from top to bottom. I spent a Saturday morning following everything that went on and I have been impressed with the work you have put in. I am no expert but I am willing to test it out. I have a work machine (running macOS) and a spare Lenovo which I use for fun. It wasn't that long ago that I blasted the whole OS away to try somehting new (XFCE) so it is my intention to do the same with this. I do use that for a few admin bits as well as experimenting with things so I need a semi working environment to work from. (Which this seems to be)

I think we can shelve the scrolling issues for now as I am pretty sure it is the Virtual Machine. I will try your suggestions when I am not on my work machine and see what I can find.

My the testing so far, once I got it booting properly I think the number of issues could be counted on one hand. The issue I am having with the VM is the host OS hogs the keybindings so I can't use it properly. This is better on Linux though as the VM takes so much control I can't get out of it so I will use that for some more testing.

> And so far even after like 10 people on that thread said they wanted it so bad and were willing to help test/debug, once I got it done it was all crickets.

I will use the VM and then prep my Linux machine to test on that. Then we will see what bugs (crickets?) turn up :)

**Comment by JoshuaCrewe** [comment] 2020-07-06 15:07
> Compositing with picom doesn't work hardly at all in virtual machines, and it makes it almost unusable (run killall compton and see if your scrolling issues go away)

I can't see any compton processes running and I can't see that picom is installed on this machine ...

`ps aux | grep compton` results in nothing being found.
`ps aux | grep picom` also results in nothing being found.

`sudo pacman -Qs picom` returns nothing as well.

What I am experiencing on this VM (on my mac) is that typing is super slow. Virtualbox on Arch has slow typing a slow janky scroll. On the trackpad you have to short sharp swipes for it to move anything.

**Comment by gardotd426** [comment] 2020-07-06 15:11
That's not anything to do with regolith then, I don't know what it could
be. Something in the VM configuration/your hardware/not having guest
modules/etc. I forgot I changed picom to an `optdepend` instead of a hard
dependency. But yeah, there's nothing in any of these packages that could
be causing that. It's just i3-gaps, some config files, a fork of i3blocks,
and a few other things like that. When I gave my VM 2 cores and 4GB of RAM
it ran completely fine once I turned compositing off.

**Comment by gardotd426** [comment] 2020-07-06 15:12
I'll create another one and see what happens, but yeah there shouldn't be
anything in these packages or any of their dependencies that cause that.

**Comment by JoshuaCrewe** [comment] 2020-07-06 16:44
OK groovy. 

> it ran completely fine once I turned compositing off
How did you turn compositing off?

I have a love/hate relationship with virtual box. I did check htop and it wasn't using all that many resources. I will get to some fiddling and check my other machine but I think it will be something to do with the config I have set up for the VM.

**Comment by gardotd426** [comment] 2020-07-06 16:59
Compositing is done by compton/picom. If you don't have it installed in
your VM, then compositing isn't on.

**Comment by JoshuaCrewe** [comment] 2020-07-07 18:19
I have cranked out the Linux laptop and running reogolith-de in there is a more representative experience. 

The scrolling is a little weird still. I whacked the setting up to max speed which helped a bunch. It just doesn't pick up on slow gentle scrolling. This is quite likely to do with running it in a VM though, so can check when I get it running on the actual hardware.

The lag when typing doesn't happen here so that was a symptom of the VM on macOS.

I am going to set a few quality of life things up on this VM and play around for a bit before wiping what I have and installing on the laptop proper.

But all in all looking Good. How do you feel about a PR for some documentation on getting it set up for testing ?

**Comment by gardotd426** [comment] 2020-07-07 18:23
Absolutely, all PRs are welcome, like I said the only real reason I haven't
done much with this the past couple weeks is because it was demoralizing
doing everything myself when I wasn't even the one that wanted to use it in
the first place (I have my own i3 setup). But I'm definitely happy to have
any PRs, I'm glad you got a more responsive experience.

Like I said, I fully plan to add remontoire-git to the dependencies once we
make it live on the AUR, it's just that until then, the way makepkg works,
I can't really do that, so you can add something to the documentation about
it but we'll remove that part when it goes live, if that makes sense.

**Comment by JoshuaCrewe** [comment] 2020-07-08 12:06
I am going through the setup to make sure I can reliably set up a working VM.

Should xorg being installed as part of this PKGBUILD ? I am installing it seperately but regolith needs it to work right?

Also do you know what is going on with the icons ?

<img width="1680" alt="Screenshot 2020-07-08 at 12 59 19" src="https://user-images.githubusercontent.com/12238901/86916494-95d0fa80-c11b-11ea-9c9e-6fc91c0b5cf6.png">

☝️ This is out of the box. They are better with the nord theme 

<img width="1680" alt="Screenshot 2020-07-08 at 13 05 57" src="https://user-images.githubusercontent.com/12238901/86916626-cb75e380-c11b-11ea-92cd-3d42b9c91b18.png">

`ttf-font-awesome` is installed by default.

**Comment by gardotd426** [comment] 2020-07-08 13:01
Xorg is in the dependencies. 


That looks like it might just be an i3xrocks issue, I don't know I'll have to look at native regolith later and check it out.

**Comment by gardotd426** [comment] 2020-07-08 13:03
From the PKGBUILD:

>    depends=('i3-gaps' 'i3status' 'xorg-server-common' 'xorg-server-devel' 'python-i3ipc' 'gnome-flashback'
>             'accountsservice' 'cups-pk-helper' 'libgtop' 'gnome-control-center' 'gnome-desktop'
>             'xorg-xwininfo' 'dbus' 'python-gobject' 'python-dbus' 'xorg-xprop' 'libev' 'pcre'
>             'libconfig' 'xcb-util-image' 'xcb-util-renderutil' 'libsigc++' 'gnome-session'
>             'gnome-settings-daemon' 'playerctl')


I got the xorg dependencies from the regular i3 package.

**Comment by JoshuaCrewe** [comment] 2020-07-10 09:14
> That looks like it might just be an i3xrocks issue, I don't know I'll have to look at native regolith later and check it out.

Some of the missing icons are just becuase there aren't any in the theme.
https://github.com/regolith-linux/regolith-styles/blob/master/nord/typeface

Thats a thing with the theme though and not with this PKGBUILD. I'll have a closer look and open an issue/PR with the theme to test. Probably better to do that in Regolith Proper though.

> I got the xorg dependencies from the regular i3 package, and I think added another couple.

Did I read somewhere that you can't have package groups as dependencies? I think you siad it in your other thread. When I install arch from nothing and this PKGBUILD I end up installing xorg as well. `xorg-server` and `xorg-xinit` from memory. Building with `makepkg -si` should go and get the dependencies right? I am not being a bit dim?

**Comment by gardotd426** [comment] 2020-07-10 10:14
`xorg-server` and `xorg-xinit` are in the dependencies already. I don't quite recall what the issue of package groups was, but IIRC I tried to just have the `xorg-apps` packagegroup as a dependency and it wouldn't work, but now I just manually grabbed the necessary xorg packages individually. So running `makepkg -si` should in fact do that.

**Comment by gardotd426** [comment] 2020-07-10 10:26
After looking, there were a couple other things missing though, so I went ahead and added them. Go ahead and pull before you test any more.

**Comment by gardotd426** [comment] 2020-07-10 10:30
But yeah I've said before this is actually one of the biggest reasons why we need a bunch of testing, because it's easy to know you have all the dependencies when you're installing on a full system, but a brand-new, fresh, minimal Arch install is another story, and while some PKGBUILDS completely leave out obvious dependencies assuming you'll have them (or maybe they're not actually needed even though some of them really seem like they are), but that's bad practice generally.

For example, none of the i3 packages list any `xorg-server` packages (`xorg-server`, `xorg-server-common`, `xorg-server-devel`) as a dependency. Don't know how you can run an X11 window manager without an X server installed, but they don't have it. I checked the rest of the xorg packages they DO list as dependencies to see if any of THOSE packages depend on `xorg-server`, in which case it would get pulled in anyway and therefore not needed in the PKGBUILD, but I couldn't find any that actually depend on `xorg-server`.

**Comment by gardotd426** [comment] 2020-07-10 10:32
But also, right now I'm going way overkill on the dependencies, a bunch of them should be in `optdepends` instead, but I don't wanna have to spend a bunch of time during testing explaining to people that they have to install `pactl` for audio control or whatever other basic shit they might need, y'know? But before I put it on the AUR I'll move it to optdepends like every other i3 package. But also, there are some things that aren't necessary for regular i3 but might be necessary for ours, so I'm hoping to find any instances of those too.

**Comment by JoshuaCrewe** [comment] 2020-07-23 16:20
So far so good. I am enjoying playing around in a VM. I am gearing up to install on real hardware as soon as I can block out some time and be confident that I am not going to bork it all up.

I think this issue has run its course now, it should be clear how to get this up and running to test now, I am happy if you want to close it in favour of more specific issues.

I don't know what is going on with some of the icons I need to do some more investigation. I got regular regolith up in a VM and I think the Icons were correct there although it doesn't help that sometimes there is no icon it is just the letter "R" or soemthing.

Which brings me on to fonts. Are fonts always so tricky in Arch? I have never manged to find a set up that works particularly well. Is there a list of fonts that everyone installs to get a reasonable looking experience? 

I use [pure promt](https://github.com/sindresorhus/pure) for example which has an icon for the arrow there. On a vanilla install of arch with just xorg, urxvt and Fira Code / Mono there is no icon. The only way I have found to get it showing is to install ttf-dejavu from trial and error. Then there is an icon but it is all jagged. It is one of the reasons I turned to a Desktop Environment in the first place (XFCE) but it doesn't seem to do things much better.

I am ranting off topic now so feel free to ignore all this.

**Comment by gardotd426** [comment] 2020-07-23 21:34
Yeah man, Nerd Fonts Complete is what you need. It's in the AUR

But I'll go ahead and close this, feel free to reopen if needed, otherwise yeah we can move to more specific stuff

**Closed by gardotd426** 2020-07-23 21:34 UTC

**Comment by JoshuaCrewe** [comment] 2020-08-17 18:09
Well. Here I am on my Thinkpad running Regolith DE in Arch using this PKGBUILD :tada: 

It worked pretty much the same as when running it in the VM but without the performance issues and other jank. 

Good Job!

**Comment by gardotd426** [comment] 2020-08-17 19:38
@JoshuaCrewe that's great news, man. 

Could you tell me if there were any issues at all with getting it up and running? Or did the PKGBUILD fully handle it? 

If the PKGBUILD is fully handling it well, then all I need to do is add the licenses (which is going to be a nightmare lol) and I might be able to actually put it on the AUR.

**Comment by JoshuaCrewe** [comment] 2020-08-17 20:04
The steps were the same as in the README. I followed the same process and it worked as expected.

At first it didn’t load the session but I think I must have typed something wrong. I cleared out the .xinitrc and re wrote it and it worked fine.

One think I would be interested in is making that session launching smoother. Should we be making a decision about a display manager and setting that up? It’s be better to run the PKGBUILD, reboot and have it present a gui login I think. Or should this be left to the user to configure? 

What’s the workflow for handling licences?

**Comment by JoshuaCrewe** [comment] 2020-08-17 20:06
There is also this thread which has cropped up,

https://fosstodon.org/@regolith/104705100455307198

If you have anything you want to communicate on there?

**Comment by gardotd426** [comment] 2020-08-17 20:23
>One think I would be interested in is making that session launching smoother. Should we be making a decision about a display manager and setting that up? It’s be better to run the PKGBUILD, reboot and have it present a gui login I think. Or should this be left to the user to configure?

This is always left to the user to configure. Packages are not to list dependencies that aren't dependencies. We can suggest an **optional** dependency for the "preferred" display manager, but no, it's out of the scope of this PKGBUILD (and bad practice) to require a display manager. That's all on the user. Same as literally every other tiling window manager (and most full desktop environments). If they don't want to manually `startx`, then they need to install a display manager, this is Arch Linux ;p

I'm perfectly fine including lightdm as an optional dependency though (especially since I'm including the regolith lightdm theme). I'll go ahead and do that. 

>What’s the workflow for handling licences?

Well, nothing regolith uses is regolith's own stuff, it's all forks (except maybe one or two packages), so the workflow is going through literally every package and finding the license for it, and then adding that to the PKGBUILD. It's just really tedious, and annoying. I'd already asked kgilmer over on the regolith github about the licensing and yeah, the answer I got was basically "yeah they're all different." 

I've been figuring out licenses here and there, but yeah for the most part we're at square 1 as far as that goes. It's not hard, it's just annoying. There are like 40 packages altogether. But yeah, I guess I can get started on actually getting some of that done. It would just help if I could get any help just with the licenses. I could easily do the PKGBUILD work myself, I just need to know what the licenses for everything are (and I mean the individual .deb's).

**Comment by gardotd426** [comment] 2020-08-17 21:06
@JoshuaCrewe Actually now that I'm going through adding the licenses I do remember there's one or two things I need to do, and yeah I could use your help on something small. 

When you use the `st` terminal package I provided in the PKGBUILD, does the theming and everything work properly? I'm also considering switching the default terminal, can you try another terminal like kitty and see if the theming works there, too? 

The regolith i3 config uses `x-terminal-emulator` which is an Ubuntu thing, but see, since I haven't patched out the part of the regolith files that SET the `x-terminal-emulator` as `st`, and I include the regolith `st` package, then it works, but I still need to fix that, because Arch doesn't use `x-terminal-emulator` (it's an `--update-alternatives` thing). 

So I intend to patch that, but before deciding whether to change the terminal emulator or keep st, I want to know how it behaves with other terminals. I'm mainly concerned only with the color themes, because other terminals set their own fonts by default so don't worry about characters missing or anything. Just the color themes, I need to know that `st` works out of the box (and that the keyboard shortcut works OOTB), and if other terminals also work with the color scheme (they should if they use .Xresources). Maybe try Xterm and urxvt.

**Comment by gardotd426** [comment] 2020-08-17 21:13
Actually now I remember I already patch the file to change `x-terminal-emulator` to `st`, but I still would like to know that information

**Comment by JoshuaCrewe** [comment] 2020-08-18 12:25
> This is always left to the user to configure. Packages are not to list dependencies that aren't dependencies. We can suggest an optional dependency for the "preferred" display manager, but no, it's out of the scope of this PKGBUILD (and bad practice) to require a display manager. That's all on the user. Same as literally every other tiling window manager (and most full desktop environments). If they don't want to manually startx, then they need to install a display manager, this is Arch Linux ;p

We make other similar decisions, like the screen locking or an application launcher etc. If its not the done thing then thats fine with me. I have always used startx in the past anyway, its just not what Regolith does right?

> I could easily do the PKGBUILD work myself, I just need to know what the licenses for everything are (and I mean the individual .deb's).

I am happy to help do some grunt work 😄 

> When you use the st terminal package I provided in the PKGBUILD, does the theming and everything work properly?

Now that you mention it I do remember some things not working as expected. At the moment I can't remember if happened when I added my own customisations to `~/.Xresources` or before. I will go back and check.

I have used urxvt for a while now and there was no theming out of the box I am pretty sure. I will confirm this though. I will try another terminal emulator and see if that one does. Launching `st` works fine using `$mod`+`enter` . When changing regolith themes there is an error that pops up about gnome terminal not being supported or something like that but I believe this has been mentioned before.

I am not on my Linux machine right now but I will create an issue with what I find.

**Comment by gardotd426** [comment] 2020-08-18 13:43
>its just not what Regolith does right?

That's because Regolith is a full Linux distribution. Of course they're going to include a display manager... This is just a port of the **Desktop Environment/Window Manager**, I'm not creating some Arch-based linux distribution version of Regolith. Just porting the desktop. 

No other window manager on Arch installs a display manager, and no full desktop environment actually depends on one.

>Now that you mention it I do remember some things not working as expected. At the moment I can't remember if happened when I added my own customisations to ~/.Xresources or before. I will go back and check.

Now, this could have been because you didn't perform the first-time setup (that's what regolith-ftue does). Check and make sure you did that first, but yeah let me know when you get back to your machine what's up.
