### ISSUE TITLE
Rofi icons

### ISSUE THREAD

**Issue by Ahanaf-Ether** [gardotd426/regolith-de#29] opened 2021-11-16 09:16 UTC
Rofi icons not appearing.

**Comment by gardotd426** [comment] 2021-11-16 11:39
Do you have a user `rofi.conf` config file that sets whether to show icons or not? Because only one of the Regolith Styles defines whether to show icons (Midnight). 

You can find out easily by `rofi -dump-config | grep icon`. 

Because I can't reproduce, I have icons here.

**Comment by Ahanaf-Ether** [comment] 2021-11-16 12:19
Alright thanks I fixed it, btw great work!

**Comment by gardotd426** [comment] 2021-11-16 13:47
Thanks! Closing

**Closed by gardotd426** 2021-11-16 13:47 UTC
