### ISSUE TITLE
Bare-metal install on MBP, report

### ISSUE THREAD

**Issue by henjen** [gardotd426/regolith-de#13] opened 2020-11-26 07:52 UTC
Joining in the testing. Fresh, bare-metal minimal install from Arch. Pulled regolith-de from git along with the optional dependencies; remontoire & picom.

OS: Arch Linux x86_64
Host: MacBookPro12,1 1.0 (2015)
Kernel: 5.9.10-arch1-1
Resolution: 2560x1600
CPU: Intel i7-5557U (4) @ 3.400GHz
GPU: Intel Iris Graphics 6100

Regolith Ubuntu (RU) version documentation is a pretty good read on the interactions from where the configs are pulled. Did find I needed a couple more X packages to help with general usage, i.e., xdg-utils & xrandr to help with hidpi stuff. Then found I could just add some args to ~/.config/regolith/Xresources for Xft.dpi and St.font and I was good to go.

If your build follows the loading order for Xresources as mentioned on RU website, it goes in this order: 
1) ~/.Xresources  (non-Regolith sessions, mentioned just to point out for other DEs on the same system I guess)
2) ~/.Xresources-regolith  (Regolith specific global themes)
3) /etc/regolith/styles/root  (Initial startup theme and config)
4) ~/.config/regolith/Xresources  (apply specific user overrides to the defaults)

So far it's going pretty well. I had some pretty terrible screen tearing going on that I believe was non-Regolith related, but I think I initially missed the part about installing picom. The optional dependency for remontoire was specifically called out with a package-mention from AUR, but I had to dig a little in #9 to find the solution. You did mention that compton is dead, however the compositor settins are in /etc/regolith/compton. Copied that directory to ~/.config/regolith/compton, then dupilcated to ~/.config/regolith/picom and the tearing has been eliminated, though I'm not entirely sure wether it's using one or the other. Had another issue with `regolith-look refresh` and with i3 reload/refresh where I had the spinning wheel of death like there was something going on in the background. Haven't seen that after picom install either. Final issues has to do with the theme (look) cahuella. I had the pair of socks as my wi-fi icon that was mentioned in another issue. Laughed my @ss of on that one, but the issue still exists somewhere in that theme. The other themes did not have the mixed up icons on the bar.
Gotta say you've done some excellent work on this. Kudos to your efforts as I think this DE is what I was looking for.

**Comment by gardotd426** [comment] 2020-11-26 11:19
>You did mention that compton is dead, however the compositor settins are in /etc/regolith/compton. Copied that directory to ~/.config/regolith/compton, then dupilcated to ~/.config/regolith/picom and the tearing has been eliminated, though I'm not entirely sure wether it's using one or the other.

Compton itself is abandoned/discontinued and is now known as picom, and up until a certain point, picom would respond to `compton` commands and also read compton configs, but yeah, the only reason regolith uses the name "compton" is because they haven't updated it, they themselves use picom on the actual regolith distro. 

 >Final issues has to do with the theme (look) cahuella. I had the pair of socks as my wi-fi icon that was mentioned in another issue. Laughed my @ss of on that one, but the issue still exists somewhere in that theme. The other themes did not have the mixed up icons on the bar.

That's weird, that was supposed to have been fixed, I can't reproduce it or anything after I updated the PKGBUILD a while back. 

>with i3 reload/refresh where I had the spinning wheel of death like there was something going on in the background.

This is an i3 "issue," not a regolith one This is why you see `--no-startup-id` in i3 configs, because that prevents the spinning wheel shit. 

>The other themes did not have the mixed up icons on the bar.

I just pushed an update, pull the changes and rebuild and reinstall and see if that changes anything for cahuella (make sure you log out and back in)

**Comment by henjen** [comment] 2020-11-28 03:26
Ok. Pulled the latest and the icons for cahuella are working correctly. I don't know what the hell I did, but now i3bar will not load the modules. Something like STATUS_COMMAND not recognized. It might be in one of the #includes in the various Xresources scattered in the system while I was trying to make adjustments. I have not had a chance yet to track it down yet. I did just build another system on an intel NUC. The Macbook Pro just seems to have other non-regolith related issues like dropping wi-fi using iwctl. I'll either uninstall that and go with NetworkManager since that seems to be integrated with regolith settings, or just do another fresh install on the partition (...because I just love the torture).

The NUC has not had any issues with regolith yet, but this hi-dpi shit on linux is a pain in the ass. I finally got that part all sorted. Maybe some specific instructions are in order for the 2560x1600 and above displays. Maybe making adjustments to .Xresources, .xinitrc, .xprofile should not be addressed before firing up regolith. Just open display settings after startx and a fresh install and see where that takes me first. Anyways, thanks for the response. I'll let you know what else I find.

**Comment by gardotd426** [comment] 2020-12-12 18:48
Go ahead and try the `1point5` branch if you don't mind and let me know how it works.

**Comment by gardotd426** [comment] 2020-12-12 18:49
Oh and starting with 1point5 branch it no longer conflicts with gnome-shell (and possibly not even gdm)

**Comment by henjen** [comment] 2020-12-17 17:52
A little help on that please. Pretty new to git, so do I clone just the branch 1point5 or the repo following the README?

**Comment by gardotd426** [comment] 2020-12-17 18:07
Run `git clone -b 1point5 https://github.com/gardotd426/regolith-de, make sure you don't do it wherever your original cloning was (or remove that folder first). Then cd into regolith-de and run `makepkg -si`. You might want to uninstall the other packages first, though it shouldn't matter as they should be replaced by these.

**Comment by gardotd426** [comment] 2020-12-17 22:19
Go ahead and pull again (go into the directory and run `git pull`), I've updated a patch. Reinstall with `makepkg -sfi`

**Comment by henjen** [comment] 2020-12-17 22:47
Okay. I cloned the 1point5 brach and could not get it to start correctly. Xorg complained about not being able to locate i3-gnome-flashback-session. I'll run the `git pull` and reinstall.

**Comment by gardotd426** [comment] 2020-12-17 23:38
Yeah I don't know what that's about because I literally just created *another* vm, this time using Manjaro XFCE's iso, and I installed literally nothing but the dependencies and this PKGBUILD and sure enough it worked as it's supposed to.

**Comment by gardotd426** [comment] 2020-12-21 23:30
I'm going to be tinkering with the patch to fix the spinny wheel thing over the next little bit, so if you could update when I'm ready and make sure it's still gone, that'd be great. The thing is, i3 has this thing in its config file used w/ `exec` commands called `--no-startup-id`, and it's what prevents the spinny wheel, but in order to quickly get rid of it I had to add `--no-startup-id` to literally every exec command in the config, and that's not ideal, so I'm going to try and find out which one(s) were causing it so I can remove the unnecessary ones. I'll keep you updated.

**Comment by henjen** [comment] 2020-12-24 04:47
I think you told me about that exec think before and I actually tried adding the --no-startup-id after every exec command and it didn't work out very well.

I'm still having problems with the 1point5 branch. I had started over with a clean install because I was using the Ubuntu Regolith for a bit to get to know it a little better. I can't get the i3xrocks bar to work yet, but haven't dug into yet. Let me know when your ready and I'll try again.

**Comment by gardotd426** [comment] 2020-12-24 11:12
I'm sorry you don't use the 1point5 branch anymore. I merged everything into Master and it's now fully working according to about 20 reports (I posted about it on r/archlinux and so a bunch more people offered to test). 

I thought I'd come back and told everyone about it, but I guess I forgot this thread. Sorry about that. 

Just use the master branch, and run `makepkg -sfi`.

**Comment by henjen** [comment] 2020-12-24 16:47
OK. That's working much better now. Thanks for the update. Quick question though: Can I still copy the /etc/regolith/i3/config file to my home directory and make changes there? I tried changing the default terminal from the home config file and it was still using the regolith-st terminal after a reload/refresh and also after logging out and back in.

**Comment by gardotd426** [comment] 2020-12-24 21:14
Read Regolith's documentation for information on user configuration. 

But basically, the Regolith i3 config file goes to `~/.config/regolith/i3/config`. Not `~/.config/i3/config`.

**Closed** 2021-09-23 00:01 UTC
