### ISSUE TITLE
Can't hide window title bars on fresh Arch install

### ISSUE THREAD

**Issue by sukulent** [gardotd426/regolith-de#44] opened 2022-06-09 14:55 UTC
Hey, firstly, thanks very much for this. Just installed arch and it kinda worked the first time.
Have a few issues with the customization tho. I got my regolith config off of my main PC and it doesn't look the same.

The biggest is that I see title bars on some windows (and the minimize maximize buttons without close are cringe). Most annoying on gnome-terminal which I like to use.
I have in my config the default_border pixel 1, also tried the old for_window [class="^.*] border pixel 0
There isn't also the red border I have set up around currently active window, although discord respects it and is working as expected. Looks like it has to do something with gnome decorating the windows. I have i3-gaps installed, hope I am using that.

Anyone knows how to get rid of a centimeter of dumb titlebar?

Also other things, not really that annoying but, (don't now if I should mash more problems into one issue, but I kinda don't want to open bunch of issues) there is no load_average i3xrocks module in /usr/share/i3xrocks, I might took this from i3blocks folder on my main PC, I am not sure, but after installing i3blocks there is no /usr/share/i3blocks to yoink it from :laughing:  ...and taking it from my main PC is a real retarded but working workaround.
And the module for showing the name of the window works fine, only when having focus on empty workspace it has some html in it, i.e.:
on my main PC I see 8: 8, but here I get 8:<span font_desc='Source Code Pro Medium 13'> 5 </span>
I installed the font but nothing changed.

**Comment by gardotd426** [comment] 2022-06-09 18:14
I can't reproduce this...

![Screenshot_20220609_141204](https://user-images.githubusercontent.com/54234607/172915913-fb23255a-ccdb-4053-a34f-adef166d71fa.png)

Note I have no border or titlebars.

>Also other things, not really that annoying but, (don't now if I should mash more problems into one issue, but I kinda don't want to open bunch of issues) there is no load_average i3xrocks module in /usr/share/i3xrocks, I might took this from i3blocks folder on my main PC

This isn't part of i3xrocks. It is likely part of i3blocks, as you said. I don't provide i3blocks script. i3xrocks is a fork, I provide exactly what Regolith provides as far as i3xrocks scripts go. 

And the module for showing the name of the window works fine, only when having focus on empty workspace it has some html in it, i.e.:
on my main PC I see 8: 8, but here I get 8: 5
I installed the font but nothing changed.

**Comment by sukulent** [comment] 2022-06-12 12:15
Thank you for your quick response.
I am sorry for bothering you, this all happened probably because of two things - one, I put in there my old janky config file from my PC and two, I had installed gnome and tried once before I had installed regolith with yay.

Also I made a mistake, the original "focused-window-name" shows "3: <span font_desc:'Source Code Pro Medium 13'> 3 </span>"
and I have the font installed.

I think I'll remove all of regolith, i3 and gnome including config files and than install just regolith and it's dependencies with yay, than I should go through my i3 config and modify the default accordingly. Also I need to look up how the Xresources thing works, I think I brute-forced my way and deleted the variables replacing them with plain hex color codes years ago, when I really didn't know what I was doing.

I tried restarting i3 with the default config, than again with my config and some things, like theme color, didn't change back so I really need to look up how to theme regolith properly. If you have some suggestions, feel free to point me somewhere, tho I think I bothered you enough with my jank.
Really sorry if this was as unnecessary issue as it seems.

**Comment by gardotd426** [comment] 2022-06-12 18:59
>I think I'll remove all of regolith, i3 and gnome including config files and than install just regolith and it's dependencies with yay, than I should go through my i3 config and modify the default accordingly. 

No no no. This is not at all the way to a solution. The default Regolith config works, don't go messing with it except to customize/add. 

But more importantly, Regolith 2.0 came out. And it changes almost everything. So you are going to want to wait until I'm done porting it over/updating the PKGBUILD. It'll just be a few days

**Comment by sukulent** [comment] 2022-06-14 11:24
Ok, thanks, I'll wait with the customization than. I only customized the bar (one needs a battery % readout) and few shortcuts so I can use it a bit.
Looked into it and it kinda seems a bit more complex than I would thought.

Thanks for the work you're doing.

Also if I can make sure and ask: I will be able to move the config to my PC, if I upgrade both to Regolith 2.0?

**Comment by gardotd426** [comment] 2022-06-15 05:23
>Also if I can make sure and ask: I will be able to move the config to my PC, if I upgrade both to Regolith 2.0?

I can't speak to anything having to do with Regolith the ***DISTRIBUTION***. I can only speak to Regolith Desktop Environment's port over to Arch Linux. I mean, a bunch of stuff has changed in 2.0, but that shouldn't change anything that would no longer make configs compatible between Regolith Linux and Arch Linux. THAT SAID - I am ONLY referring to configurations that are properly formatted, updated, and confirmed to work with the new 2.0 way of doing things. 

Like, your old config file? It's dead. Don't delete it, because you'll want it for reference, but I'm just telling you. Regolith 2.0 puts its i3 configurations in like 6 or 7 different smaller files. Plus GNOME's update to GNOME 42 has broken the current i3/regolith method of opening `gnome-control-center` windows (So like Super+D doesn't open the Display options, etc). I've already found the source of the problem, and I shouldn't have to change anything myself, it should be fixed once all the package s coming from Regolith get updated, but it's honestly just really tedious. 

Like, if you look at the PKGBUILD, it's like 500 something lines of just tedium, and now I get to go through and confirm which of those .deb packages are still going to be used, *update* their version numbers, update their sha256sums, remove the packages that no longer exist or have been replaced, for like over 100 packages. Then I have to make sure that everything compiles, and that it actually works the way it should (meaning a user can just install the packages, select "Regolith" from their login manager, and login to a functioning Regolith Desktop Environment session). I have on multiple occasions had to create quite a few patches to change the way the sessions were initiated on Regolith vs Arch since they aren't the same distro and aren't even related in any way. 

So I'm working on it, and trying to automate it as best I can. I'm kicking myself for agreeing to split every i3xrocks module into its own package a few months back though, someone complained saying they should all be their own package, and now I get to add a ton more, along with adding completely new shit like iago. But it's nothing I can't do, it's just very, very tedious.

**Comment by sukulent** [comment] 2022-06-15 11:19
I think I liked the one config file way of doing things more than this, but okay, it is what it is.
I have old Debian Buster with hacked-in Ubuntu Regolith from before the time there was any proper "Debian version" - and it works well. I have postponed upgrading to newer versions of Debian as that would break Regolith immediately and I didn't feel like setting it up again. But now I am trying arch on my laptop and I want to configure Regolith properly, then it should be ok to move the configuration to my fully updated PC with fresh Regolith 2.0 so I can have it finally set up properly  :D (hopefully there'll be some comprehensive guide, didn't found much, except the table of all the config files and how it loads theme)

Again, thank you for your work on this.
It's probably time to close this issue now, all my problems were probably just because I tried to use my old config and I'll wait for the 2.0.
I'd like to help, but I have little experience with arch, so I think I could only do some testing if you'd want.

**Closed** 2023-02-23 08:27 UTC
